name: Run tests

on: 
  push:
    branches:
      - main
    paths:
      - services/**
  pull_request:
  workflow_dispatch:

jobs:
  filter:
    runs-on: ubuntu-24.04
    outputs:
      services: ${{ steps.filter.outputs.changes }}
    steps:
      - name: checkout the code
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0
        
      - name: filter
        id: filter
        uses: dorny/paths-filter@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          filters: .github/utils/file-filters.yml

  tests:
    if: ${{ needs.filter.outputs.services != '[]' && needs.filter.outputs.services != ' ' }}
    strategy:
      fail-fast: false
      matrix:
        services: ${{ fromJson(needs.filter.outputs.services) }}
          #  [
          #  "services/node/api-node", 
          #  "services/go/api-golang",
          #  "services/python/load-generator-python",
          #  "services/react/client-react" ]
    runs-on: ubuntu-24.04
    needs: filter
    steps:
      - name: checkout the code
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0

      - name: setup node environment
        if: ${{ matrix.services == 'services/node/api-node' || startsWith(matrix.services, 'services/react')}}
        uses: actions/setup-node@48b55a011bda9f5d6aeb4c2d9c7362e8dae4041e
        with:
          node-version-file: ${{ matrix.services }}/package.json
          cache-dependency-path: ${{ matrix.services }}/package-lock.json
          cache: "npm"

      - name: set up poetry
        if: ${{ startsWith(matrix.services, 'services/python/load-generator-python') }}
        uses: snok/install-poetry@v1


      - name: setup python environment
        if: ${{ startsWith(matrix.services, 'services/python/load-generator-python') }}
        uses: actions/setup-python@ece7cb06caefa5fff74198d8649806c4678c61a1
        with:
          cache: 'poetry'
          python-version-file: ${{ matrix.services }}/pyproject.toml
          cache-dependency-path: ${{ matrix.services }}/poetry.lock 

      - name: setup go environment
        if: ${{ matrix.services == 'services/go/api-golang'}}
        uses: actions/setup-go@924ae3a1cded613372ab5595356fb5720e22ba16
        with:
          go-version-file: services/go/api-golang/go.mod
          cache-dependency-path: services/go/api-golang/go.sum
          cache: true

      - name: Install Task
        uses: go-task/setup-task@v2
        with:
          version: 3.44.1
      
      - name: install app dependencies
        working-directory: ${{ matrix.services }}
        run: |
          task install-ci

      - name: run tests
        working-directory: ${{ matrix.services }}
        run: |
          task tests
        

  